services:
  app:
    build:
      context: .
      target: development
    environment:
      - ENVIRONMENT=development
      - DEBUG=1
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
      - "5678:5678"  # For debugger 